# Numpy:Package for Multidimensiol array

In [72]:
import numpy as np

In [38]:
simple_list=[6,4,3]
np.array(simple_list)

array([6, 4, 3])

In [6]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [8]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(5,65)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64])

In [10]:
np.arange(1,30,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [8]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.arange(1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [11]:
np.arange(51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [14]:
np.arange(5,30,5)

array([ 5, 10, 15, 20, 25])

In [15]:
np.arange(5,26,5)

array([ 5, 10, 15, 20, 25])

In [18]:
np.zeros(100,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.ones(54,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [29]:
np.ones((3,8),int)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [30]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [33]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [4]:
np.eye((10),dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [5]:
np.random.rand(2,3)

array([[0.37082026, 0.30557124, 0.06691302],
       [0.35297887, 0.49275317, 0.29929776]])

In [8]:
arr=np.random.rand(2,4)
arr

array([[0.50531514, 0.41159237, 0.91665287, 0.71298169],
       [0.3226526 , 0.36271491, 0.40842611, 0.33006715]])

In [12]:
np.random.randint(2,10)

6

In [13]:
np.random.randint(20,50,100)

array([48, 41, 37, 38, 37, 41, 41, 20, 21, 37, 47, 30, 23, 41, 41, 20, 39,
       38, 23, 36, 26, 21, 48, 22, 29, 41, 35, 26, 36, 25, 29, 30, 35, 49,
       28, 36, 31, 26, 35, 44, 41, 46, 34, 44, 46, 41, 46, 37, 39, 27, 23,
       41, 25, 35, 29, 49, 23, 34, 20, 22, 40, 39, 38, 23, 42, 20, 37, 43,
       25, 40, 40, 35, 41, 23, 40, 26, 28, 39, 36, 29, 47, 26, 33, 36, 40,
       27, 34, 24, 35, 36, 37, 49, 45, 30, 23, 41, 36, 44, 38, 40])

In [30]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [31]:
rand_array=np.random.randint(0,100,20)
rand_array

array([12, 45, 28, 96, 39, 52,  6, 23, 45, 18, 50, 70, 65,  3, 71, 51, 22,
       50, 74, 41])

In [37]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [39]:
rand_array.min()

3

In [40]:
rand_array.argmin()

13

In [41]:
rand_array.max()

96

In [47]:
rand_array.argmax()

3

In [49]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
a=np.random.rand(2,3)
a

array([[0.87055906, 0.47075693, 0.12227215],
       [0.75768107, 0.67947097, 0.77495742]])

In [54]:
a.T

array([[0.87055906, 0.75768107],
       [0.47075693, 0.67947097],
       [0.12227215, 0.77495742]])

In [56]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [60]:
sample_array[9]

19

In [62]:
sample_array[2:5]

array([12, 13, 14])

In [86]:
sample_array[1:4]
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [78]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [85]:
sample_array[0:6]

array([10, 11, 12, 13, 14, 15])

In [87]:
subject_sample_array=sample_array[0:7]
subject_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [88]:
subject_sample_array[:]=1001
subject_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# Two Dimensional array

In [89]:
 import numpy as np

In [90]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [91]:
sample_matrix[0,2]

1

In [92]:
sample_matrix[1,2]

21

In [94]:
sample_matrix[1,:]

array([24, 23, 21, 33])

In [97]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

# selection techniques

In [99]:
sample_array=np.arange(1,20)

In [100]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [101]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [103]:
np.exp(sample_array)  # exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [104]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [105]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [106]:
np.max(sample_array)

19

In [107]:
np.min(sample_array)

1

In [108]:
np.argmax(sample_array)

18

In [109]:
np.argmin(sample_array)

0

In [112]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [113]:
np.std(sample_array)

5.477225575051661

In [114]:
np.var(sample_array)

30.0

In [115]:
np.mean(sample_array)

10.0

In [117]:
array=np.random.rand(3,5)
array

array([[0.75695892, 0.99405579, 0.36292627, 0.26649959, 0.47741379],
       [0.72059704, 0.29430478, 0.4607419 , 0.61338132, 0.07981719],
       [0.2460236 , 0.73305906, 0.61968774, 0.39132806, 0.29262756]])

In [119]:
np.round(array,decimals=2)

array([[0.76, 0.99, 0.36, 0.27, 0.48],
       [0.72, 0.29, 0.46, 0.61, 0.08],
       [0.25, 0.73, 0.62, 0.39, 0.29]])

In [121]:
sports=np.array(['golf','football','cricket',])
np.unique(sports)

array(['cricket', 'football', 'golf'], dtype='<U8')